name: Build and Deploy

on:
  push:
    branches:
      - 'master'
jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DO_API_KEY }}
        password: ${{ secrets.DO_API_KEY }}

    - name: Build and push up
      uses: docker/build-push-action@v4
      with:
        file: Dockerfile
        context: .
        push: true
        tags: registry.digitalocean.com/to-be-united/frontend:latest
        labels: api-server
